version: "3.9"
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped
    
  streamlit:
    build: .  # path to your Streamlit Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379